trigger:
  - preprod

pool:
  name: 'Default'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    name: Default
    demands:
      - agent.name -equals selfhosted

  steps:
  - checkout: self
    fetchDepth: 0

  - task: HelmInstaller@1
    inputs:
      helmVersion: '3.15.2'

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: 'preprod-deploy'
      namespace: 'preprod'
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './news-app'
      releaseName: 'newsapp'
      install: true
      valueFile: './values/news-app/preprod/values.yaml'
