trigger:
  - sandbox
  - preprod

pool:
  name: 'Default'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  pool:
    name: Default
    demands:
      - agent.name -equals selfhosted

  steps:
  - checkout: self
    fetchDepth: 0

  - task: HelmInstaller@1
    inputs:
      helmVersion: '3.15.2'

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceConnection: '$(Build.SourceBranchName)-deploy'
      namespace: '$(Build.SourceBranchName)'
      command: 'upgrade'
      chartType: 'FilePath'
      chartPath: './news-app'
      releaseName: 'newsapp'
      install: true
      valueFile: './values/news-app/$(Build.SourceBranchName)/values.yaml'
